---
- name: Deploy artifact
  hosts: tomcat
  become: yes
  
  tasks:
    - name: download maven artifact
      maven_artifact:
      group_id: test.app
      artifact_id: test_java
      repository_url: 'http://34.133.235.108:8081/repository/java-test/'
      username: java-project
      password: java-project
      dest: /tmp/test-java.jar
